name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
          image: mariadb:latest
          env:
              MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
              MARIADB_USER: websmtp
              MARIADB_PASSWORD: websmtp
              MARIADB_DATABASE: websmtp
          ports:
              - 3306:3306
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Migrate Database
      run: dotnet run --mgirate-database
    - name: Test
      run: dotnet test --no-build --verbosity normal
