name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout & Restore/Build/Publish
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build websmtp --no-restore
    - name: Publish
      run: dotnet publish websmtp -o ./build/

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}

    - name: Build Spam Assassin Docker image
      working-directory: ./spamassassin
      run: docker build -t yvansolutions/spamassassin:latest .
 
    - name: Push Assassin Docker image
      working-directory: ./spamassassin
      run: docker push yvansolutions/spamassassin:latest

    - name: Build Websmtp Docker image
      run: docker build -t yvansolutions/websmtp:latest .

    - name: Push Websmtp Docker image
      working-directory: ./spamassassin
      run: docker push yvansolutions/websmtp:latest
